# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: G:/XilinxPrograms/2024_finger/2024_finger.srcs/sources_1/bd/design_finger/ip/design_finger_axi_gpio_1_0/design_finger_axi_gpio_1_0.xci
# IP: The module: 'design_finger_axi_gpio_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/XilinxPrograms/2024_finger/2024_finger.srcs/sources_1/bd/design_finger/ip/design_finger_axi_gpio_1_0/design_finger_axi_gpio_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_finger_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: g:/XilinxPrograms/2024_finger/2024_finger.srcs/sources_1/bd/design_finger/ip/design_finger_axi_gpio_1_0/design_finger_axi_gpio_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_finger_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: g:/XilinxPrograms/2024_finger/2024_finger.srcs/sources_1/bd/design_finger/ip/design_finger_axi_gpio_1_0/design_finger_axi_gpio_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_finger_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: G:/XilinxPrograms/2024_finger/2024_finger.srcs/sources_1/bd/design_finger/ip/design_finger_axi_gpio_1_0/design_finger_axi_gpio_1_0.xci
# IP: The module: 'design_finger_axi_gpio_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/XilinxPrograms/2024_finger/2024_finger.srcs/sources_1/bd/design_finger/ip/design_finger_axi_gpio_1_0/design_finger_axi_gpio_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_finger_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: g:/XilinxPrograms/2024_finger/2024_finger.srcs/sources_1/bd/design_finger/ip/design_finger_axi_gpio_1_0/design_finger_axi_gpio_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_finger_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: g:/XilinxPrograms/2024_finger/2024_finger.srcs/sources_1/bd/design_finger/ip/design_finger_axi_gpio_1_0/design_finger_axi_gpio_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_finger_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
